# These are supported funding model platforms

github: anshuparik # GitHub Sponsors (international)
buy_me_a_coffee: anshupareek # Optional, when supported in India
custom: # https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
  - https://github.com/sponsors/anshuparik
